import { NextRequest, NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'
import type { DetectionRule } from '@/lib/types'

export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient()
    let user = null
    try { const { data } = await supabase.auth.getUser(); user = data.user }
    catch { const { data } = await supabase.auth.getSession(); user = data.session?.user ?? null }
    if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

    const { rule } = await req.json() as { rule: DetectionRule }
    if (!rule) return NextResponse.json({ error: 'Rule required' }, { status: 400 })

    // Get GitHub PAT
    const sb = createServiceClient()
    const { data: keyData } = await sb.from('user_api_keys')
      .select('api_key').eq('user_id', user.id).eq('provider', 'github').maybeSingle()

    if (!keyData?.api_key) return NextResponse.json({ error: 'Add your GitHub Personal Access Token in Settings first.' }, { status: 400 })

    const ext = rule.platform.includes('KQL') ? 'kql' : rule.platform.includes('SPL') ? 'spl' : rule.platform.includes('EQL') ? 'eql' : rule.platform.includes('XML') ? 'xml' : 'txt'
    const filename = `${rule.title.replace(/[^a-z0-9]/gi,'_').toLowerCase()}.${ext}`
    const content = [
      `# ${rule.title}`,
      `# Platform: ${rule.platform}`,
      `# MITRE: ${rule.mitre_id} — ${rule.mitre_name}`,
      `# Tactic: ${rule.tactic}`,
      `# Severity: ${rule.severity}`,
      `# Generated by SentinelDetect — smartswingalerts.com`,
      '',
      rule.rule,
      '',
      `# Description: ${rule.description}`,
    ].join('\n')

    const res = await fetch('https://api.github.com/gists', {
      method: 'POST',
      headers: { Authorization: `Bearer ${keyData.api_key}`, 'Content-Type': 'application/json', Accept: 'application/vnd.github+json' },
      body: JSON.stringify({
        description: `SentinelDetect: ${rule.title} (${rule.mitre_id})`,
        public: false,
        files: { [filename]: { content } },
      }),
    })
    const gist = await res.json()
    if (!res.ok) throw new Error(gist.message || 'GitHub API error')
    return NextResponse.json({ url: gist.html_url, id: gist.id })
  } catch (err: unknown) {
    return NextResponse.json({ error: err instanceof Error ? err.message : 'Gist export failed' }, { status: 500 })
  }
}
