'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

const MITRE = [
  {tactic:'Initial Access',    id:'TA0001', techs:['T1078','T1566','T1190','T1133','T1195']},
  {tactic:'Execution',         id:'TA0002', techs:['T1059.001','T1059.003','T1047','T1053','T1204']},
  {tactic:'Persistence',       id:'TA0003', techs:['T1547','T1053','T1098','T1543','T1136']},
  {tactic:'Privilege Esc.',    id:'TA0004', techs:['T1548','T1134','T1055','T1068','T1078']},
  {tactic:'Defense Evasion',   id:'TA0005', techs:['T1070','T1036','T1112','T1562','T1027']},
  {tactic:'Credential Access', id:'TA0006', techs:['T1003.001','T1558.003','T1110','T1555','T1557']},
  {tactic:'Discovery',         id:'TA0007', techs:['T1087','T1082','T1046','T1083','T1069']},
  {tactic:'Lateral Movement',  id:'TA0008', techs:['T1021.001','T1550.002','T1021.002','T1080']},
  {tactic:'Collection',        id:'TA0009', techs:['T1114','T1056','T1115','T1530','T1213']},
  {tactic:'C2',                id:'TA0011', techs:['T1071.004','T1071.001','T1572','T1090']},
  {tactic:'Exfiltration',      id:'TA0010', techs:['T1041','T1048','T1567','T1052']},
  {tactic:'Impact',            id:'TA0040', techs:['T1486','T1490','T1489','T1485','T1499']},
]

interface GroupData {
  id:string;name:string;aliases:string[];country:string;motivation:string
  sectors:string[];techniques:string[];color:string
  coverage_count:number;coverage_pct:number
  covered_techniques:string[];gap_techniques:string[]
}

export default function MatrixPage() {
  const [covered,   setCovered]   = useState<Set<string>>(new Set())
  const [ruleMap,   setRuleMap]   = useState<Record<string,string>>({})
  const [loading,   setLoading]   = useState(true)
  const [hovered,   setHovered]   = useState<string|null>(null)
  const [groups,    setGroups]    = useState<GroupData[]>([])
  const [selGroup,  setSelGroup]  = useState<GroupData|null>(null)
  const [groupsTab, setGroupsTab] = useState(false)
  const [groupsLoading, setGroupsLoading] = useState(false)

  useEffect(() => {
    async function load() {
      const sb = createClient()
      const { data } = await sb.from('rules').select('mitre_id, title')
      if (data) {
        const s = new Set<string>()
        const m: Record<string,string> = {}
        data.forEach((r: any) => {
          if (r.mitre_id) {
            s.add(r.mitre_id.toUpperCase())
            s.add(r.mitre_id.split('.')[0].toUpperCase())
            m[r.mitre_id.toUpperCase()] = r.title
          }
        })
        setCovered(s); setRuleMap(m)
      }
      setLoading(false)
    }
    load()
  }, [])

  async function loadGroups() {
    if (groups.length > 0) return
    setGroupsLoading(true)
    const r = await fetch('/api/mitre/groups')
    if (r.ok) { const d = await r.json(); setGroups(d.groups || []) }
    setGroupsLoading(false)
  }

  useEffect(() => { if (groupsTab) loadGroups() }, [groupsTab])

  function exportNavigator() {
    const techniques = Array.from(covered).filter(t => t.includes('.')).map(id => ({
      techniqueID: id, color: '#f97316', comment: 'Covered by SentinelDetect', enabled: true, score: 100,
    }))
    const nav = { name:'SentinelDetect Coverage', versions:{attack:'14',navigator:'4.9',layer:'4.5'},
      domain:'enterprise-attack', description:'Generated by SentinelDetect', techniques,
      gradient:{colors:['#f9f9f9','#f97316'],minValue:0,maxValue:100} }
    const a = document.createElement('a')
    a.href = URL.createObjectURL(new Blob([JSON.stringify(nav,null,2)],{type:'application/json'}))
    a.download = 'sentineldetect-navigator-layer.json'; a.click()
  }

  const totalTechs   = MITRE.reduce((a,t) => a + t.techs.length, 0)
  const coveredCount = MITRE.reduce((a,t) => a + t.techs.filter(id => covered.has(id.toUpperCase())).length, 0)
  const pct          = Math.round(coveredCount / totalTechs * 100)

  // Technique colouring logic
  function getCellStyle(tid: string) {
    const upper = tid.toUpperCase()
    const base  = upper.split('.')[0]
    const isCov = covered.has(upper) || covered.has(base)
    const isHov = hovered === tid

    // When a group is selected, show group-specific colouring
    if (selGroup) {
      const inGroup = selGroup.techniques.some(t =>
        t.toUpperCase() === upper || t.split('.')[0].toUpperCase() === base
      )
      if (!inGroup) return {
        bg: 'var(--bg3)', color: 'var(--muted2)',
        border: '1px solid transparent', opacity: 0.4
      }
      if (isCov) return { bg:'rgba(52,211,153,.2)', color:'var(--green)', border:'1px solid rgba(52,211,153,.4)' }
      return { bg:`${selGroup.color}22`, color: selGroup.color, border:`1px solid ${selGroup.color}55` }
    }

    if (isCov) return { bg:'rgba(52,211,153,.15)', color:'var(--green)', border:'1px solid rgba(52,211,153,.3)' }
    if (isHov) return { bg:'rgba(249,115,22,.12)', color:'#f97316', border:'1px solid rgba(249,115,22,.3)' }
    return { bg:'var(--bg3)', color:'var(--muted2)', border:'1px solid transparent' }
  }

  if (loading) return (
    <div style={{display:'flex',alignItems:'center',justifyContent:'center',minHeight:'60vh',color:'var(--muted)',fontSize:'.88rem'}}>
      Loading coverage data...
    </div>
  )

  return (
    <div style={{padding:'1.4rem'}}>

      {/* Tab bar */}
      <div style={{display:'flex',gap:'.35rem',borderBottom:'1px solid var(--border)',paddingBottom:'.75rem',marginBottom:'1.25rem'}}>
        {[false,true].map(isGroup => (
          <button key={String(isGroup)} onClick={()=>setGroupsTab(isGroup)}
            style={{padding:'.45rem 1.1rem',borderRadius:8,border:'none',fontFamily:'inherit',fontSize:'.85rem',cursor:'pointer',
              background:groupsTab===isGroup?'rgba(249,115,22,.15)':'transparent',
              color:groupsTab===isGroup?'#f97316':'var(--muted)',
              fontWeight:groupsTab===isGroup?600:400}}>
            {isGroup ? 'Threat Groups' : 'Coverage Matrix'}
          </button>
        ))}
        {!groupsTab && (
          <button onClick={exportNavigator} style={{marginLeft:'auto',padding:'.4rem .85rem',borderRadius:7,border:'1px solid var(--border)',background:'var(--bg4)',color:'var(--muted)',fontSize:'.72rem',cursor:'pointer',fontFamily:'inherit'}}>
            Export Navigator JSON
          </button>
        )}
      </div>

      {/* ── COVERAGE MATRIX TAB ─────────────────────────────────────────── */}
      {!groupsTab && (
        <>
          <div style={{display:'flex',gap:'1rem',marginBottom:'1.25rem',flexWrap:'wrap',alignItems:'center'}}>
            {[
              {n:coveredCount, l:'Techniques covered', c:'var(--green)'},
              {n:totalTechs-coveredCount, l:'Gaps remaining', c:'var(--muted2)'},
              {n:`${pct}%`, l:'Coverage', c:'#f97316'},
              {n:MITRE.length, l:'Tactics tracked', c:'var(--blue)'},
            ].map((s,i) => (
              <div key={i} style={{background:'var(--bg4)',border:'1px solid var(--border)',borderRadius:10,padding:'.75rem 1.1rem',minWidth:120}}>
                <div style={{fontSize:'1.5rem',fontWeight:800,color:s.c,letterSpacing:'-.02em'}}>{s.n}</div>
                <div style={{fontSize:'.68rem',color:'var(--muted)',textTransform:'uppercase',letterSpacing:'.07em',marginTop:'.1rem'}}>{s.l}</div>
              </div>
            ))}
            <div style={{flex:1,minWidth:200,background:'var(--bg4)',border:'1px solid var(--border)',borderRadius:10,padding:'.75rem 1.1rem',display:'flex',alignItems:'center',gap:'1rem'}}>
              <div style={{flex:1,background:'var(--bg3)',borderRadius:999,height:8,overflow:'hidden'}}>
                <div style={{width:`${pct}%`,height:'100%',background:'#f97316',borderRadius:999,transition:'width .5s ease'}}/>
              </div>
              <span style={{fontSize:'.75rem',color:'var(--muted)',fontFamily:'var(--font-mono)',flexShrink:0}}>{pct}%</span>
            </div>
          </div>

          <div style={{display:'flex',gap:'1rem',marginBottom:'1rem',flexWrap:'wrap',alignItems:'center'}}>
            {[['#34d399','Covered'],['var(--bg3)','Not covered']].map(([c,l]) => (
              <div key={l} style={{display:'flex',alignItems:'center',gap:'.4rem',fontSize:'.72rem',color:'var(--muted)'}}>
                <span style={{width:10,height:10,borderRadius:2,background:c,flexShrink:0}}/>{l}
              </div>
            ))}
            <div style={{marginLeft:'auto',display:'flex',gap:'.5rem',alignItems:'center'}}>
              <span style={{fontSize:'.75rem',color:'var(--muted)'}}>Filter by threat group:</span>
              <select value={selGroup?.name||''} onChange={e=>setSelGroup(groups.find(g=>g.name===e.target.value)||null)}
                style={{background:'var(--bg4)',border:'1px solid var(--border2)',borderRadius:7,padding:'.35rem .65rem',color:'var(--text)',fontSize:'.78rem',fontFamily:'inherit',outline:'none',cursor:'pointer'}}>
                <option value=''>All techniques</option>
                {groups.map(g=><option key={g.id} value={g.name}>{g.name} ({g.country})</option>)}
              </select>
              {selGroup && (
                <div style={{display:'flex',alignItems:'center',gap:'.5rem',padding:'.35rem .85rem',background:`${selGroup.color}18`,border:`1px solid ${selGroup.color}44`,borderRadius:7}}>
                  <span style={{width:8,height:8,borderRadius:'50%',background:selGroup.color,flexShrink:0}}/>
                  <span style={{fontSize:'.75rem',color:selGroup.color,fontWeight:600}}>{selGroup.coverage_count}/{selGroup.techniques.length} techniques ({selGroup.coverage_pct}% covered)</span>
                </div>
              )}
            </div>
          </div>

          {selGroup && selGroup.gap_techniques.length > 0 && (
            <div style={{background:'rgba(249,115,22,.06)',border:'1px solid rgba(249,115,22,.2)',borderRadius:10,padding:'.85rem 1rem',marginBottom:'1rem'}}>
              <div style={{fontSize:'.75rem',fontWeight:600,color:'#f97316',marginBottom:'.4rem'}}>
                Coverage gaps for {selGroup.name} — {selGroup.gap_techniques.length} techniques not covered
              </div>
              <div style={{display:'flex',gap:'.4rem',flexWrap:'wrap'}}>
                {selGroup.gap_techniques.map(t => (
                  <button key={t} onClick={()=>{window.location.href=`/generate?prefill=${encodeURIComponent(`Detect MITRE ATT&CK technique ${t} used by ${selGroup.name}`)}`}}
                    style={{padding:'.22rem .55rem',borderRadius:5,background:'rgba(249,115,22,.12)',border:'1px solid rgba(249,115,22,.3)',color:'#f97316',fontSize:'.68rem',fontFamily:'monospace',cursor:'pointer'}}>
                    {t} →
                  </button>
                ))}
              </div>
            </div>
          )}

          <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(140px,1fr))',gap:'.6rem'}}>
            {MITRE.map(tactic => {
              const coveredInTactic = tactic.techs.filter(id => covered.has(id.toUpperCase())||covered.has(id.split('.')[0].toUpperCase())).length
              return (
                <div key={tactic.id} style={{background:'var(--bg4)',border:'1px solid var(--border)',borderRadius:10,overflow:'hidden'}}>
                  <div style={{padding:'.45rem .6rem',borderBottom:'1px solid var(--border)',background:coveredInTactic>0?'rgba(52,211,153,.08)':'var(--bg3)',display:'flex',alignItems:'center',justifyContent:'space-between'}}>
                    <span style={{fontSize:'.62rem',fontWeight:700,textTransform:'uppercase',letterSpacing:'.07em',color:'var(--muted)'}}>{tactic.tactic}</span>
                    <span style={{fontSize:'.58rem',fontFamily:'var(--font-mono)',color:coveredInTactic>0?'var(--green)':'var(--muted2)'}}>{coveredInTactic}/{tactic.techs.length}</span>
                  </div>
                  <div style={{padding:'.4rem .5rem',display:'flex',flexDirection:'column',gap:'.28rem'}}>
                    {tactic.techs.map(tid => {
                      const cs = getCellStyle(tid)
                      const isCov = covered.has(tid.toUpperCase())||covered.has(tid.split('.')[0].toUpperCase())
                      return (
                        <div key={tid}
                          onMouseEnter={()=>setHovered(tid)} onMouseLeave={()=>setHovered(null)}
                          title={isCov?`✓ ${ruleMap[tid.toUpperCase()]||tid}`:`No rule for ${tid} — click to generate`}
                          onClick={()=>{ if(!isCov) window.location.href=`/generate?prefill=${encodeURIComponent(`Detect MITRE ATT&CK technique ${tid} (${tactic.tactic})${selGroup?` — used by ${selGroup.name}`:''}`)}` }}
                          style={{padding:'.22rem .45rem',borderRadius:4,fontSize:'.63rem',fontFamily:'var(--font-mono)',cursor:isCov?'default':'pointer',transition:'all .12s',display:'flex',alignItems:'center',justifyContent:'space-between',gap:'.3rem',
                            background:cs.bg, color:cs.color, border:cs.border, opacity:(cs as any).opacity}}>
                          <span>{tid}</span>
                          {isCov && <span style={{fontSize:'.55rem'}}>✓</span>}
                        </div>
                      )
                    })}
                  </div>
                </div>
              )
            })}
          </div>
          <p style={{marginTop:'1.25rem',fontSize:'.72rem',color:'var(--muted2)'}}>Click any uncovered technique to pre-fill a scenario and generate a rule for it.</p>
        </>
      )}

      {/* ── THREAT GROUPS TAB ───────────────────────────────────────────── */}
      {groupsTab && (
        <>
          {groupsLoading && <div style={{color:'var(--muted)',textAlign:'center',padding:'3rem',fontSize:'.85rem'}}>Loading threat groups…</div>}
          {!groupsLoading && (
            <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(300px,1fr))',gap:'1rem'}}>
              {groups.map(g => (
                <div key={g.id} style={{background:'var(--bg4)',border:`1px solid ${g.color}33`,borderRadius:12,overflow:'hidden',borderLeft:`3px solid ${g.color}`}}>
                  <div style={{padding:'1rem 1.1rem',borderBottom:'1px solid var(--border)'}}>
                    <div style={{display:'flex',alignItems:'flex-start',justifyContent:'space-between',marginBottom:'.4rem'}}>
                      <div>
                        <div style={{fontWeight:700,fontSize:'.9rem',color:'var(--text)'}}>{g.name}</div>
                        <div style={{fontSize:'.72rem',color:'var(--muted)',marginTop:'.15rem'}}>{g.aliases.slice(0,2).join(' · ')}</div>
                      </div>
                      <span style={{fontSize:'.68rem',padding:'.15rem .55rem',borderRadius:6,background:`${g.color}22`,color:g.color,border:`1px solid ${g.color}44`,fontWeight:600,flexShrink:0}}>{g.country}</span>
                    </div>
                    <div style={{display:'flex',gap:'.35rem',flexWrap:'wrap',marginTop:'.5rem'}}>
                      {g.sectors.slice(0,3).map(s=>(
                        <span key={s} style={{fontSize:'.62rem',padding:'.1rem .45rem',borderRadius:4,background:'var(--bg)',border:'1px solid var(--border)',color:'var(--muted)'}}>{s}</span>
                      ))}
                      <span style={{fontSize:'.62rem',color:'var(--muted2)',alignSelf:'center'}}>{g.motivation}</span>
                    </div>
                  </div>
                  <div style={{padding:'.85rem 1.1rem'}}>
                    <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:'.65rem'}}>
                      <span style={{fontSize:'.75rem',color:'var(--muted)'}}>Your coverage</span>
                      <span style={{fontSize:'.85rem',fontWeight:700,color:g.coverage_pct>=50?'var(--green)':g.coverage_pct>=25?'#f97316':'var(--red)'}}>{g.coverage_pct}%</span>
                    </div>
                    <div style={{background:'var(--bg)',borderRadius:999,height:6,overflow:'hidden',marginBottom:'.75rem'}}>
                      <div style={{width:`${g.coverage_pct}%`,height:'100%',background:g.coverage_pct>=50?'var(--green)':g.coverage_pct>=25?'#f97316':'var(--red)',borderRadius:999,transition:'width .5s'}}/>
                    </div>
                    <div style={{fontSize:'.72rem',color:'var(--muted)',marginBottom:'.5rem'}}>{g.coverage_count}/{g.techniques.length} techniques covered · {g.gap_techniques.length} gaps</div>
                    {g.gap_techniques.length > 0 && (
                      <button onClick={()=>{setGroupsTab(false);setSelGroup(g)}}
                        style={{width:'100%',padding:'.45rem',borderRadius:7,border:`1px solid ${g.color}44`,background:`${g.color}11`,color:g.color,fontSize:'.78rem',cursor:'pointer',fontFamily:'inherit',fontWeight:600}}>
                        View gaps in matrix →
                      </button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </>
      )}
    </div>
  )
}
