'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

const MITRE = [
  {tactic:'Initial Access',    id:'TA0001', techs:['T1078','T1566','T1190','T1133','T1195']},
  {tactic:'Execution',         id:'TA0002', techs:['T1059.001','T1059.003','T1047','T1053','T1204']},
  {tactic:'Persistence',       id:'TA0003', techs:['T1547','T1053','T1098','T1543','T1136']},
  {tactic:'Privilege Esc.',    id:'TA0004', techs:['T1548','T1134','T1055','T1068','T1078']},
  {tactic:'Defense Evasion',   id:'TA0005', techs:['T1070','T1036','T1112','T1562','T1027']},
  {tactic:'Credential Access', id:'TA0006', techs:['T1003.001','T1558.003','T1110','T1555','T1557']},
  {tactic:'Discovery',         id:'TA0007', techs:['T1087','T1082','T1046','T1083','T1069']},
  {tactic:'Lateral Movement',  id:'TA0008', techs:['T1021.001','T1550.002','T1021.002','T1080']},
  {tactic:'Collection',        id:'TA0009', techs:['T1114','T1056','T1115','T1530','T1213']},
  {tactic:'C2',                id:'TA0011', techs:['T1071.004','T1071.001','T1572','T1090']},
  {tactic:'Exfiltration',      id:'TA0010', techs:['T1041','T1048','T1567','T1052']},
  {tactic:'Impact',            id:'TA0040', techs:['T1486','T1490','T1489','T1485','T1499']},
]

export default function MatrixPage() {
  const [covered,  setCovered]  = useState<Set<string>>(new Set())
  const [ruleMap,  setRuleMap]  = useState<Record<string, string>>({})
  const [loading,  setLoading]  = useState(true)
  const [hovered,  setHovered]  = useState<string|null>(null)

  useEffect(() => {
    async function load() {
      const sb = createClient()
      const { data } = await sb.from('rules').select('mitre_id, title')
      if (data) {
        const s = new Set<string>()
        const m: Record<string, string> = {}
        data.forEach((r: any) => {
          if (r.mitre_id) {
            s.add(r.mitre_id.toUpperCase())
            m[r.mitre_id.toUpperCase()] = r.title
          }
        })
        setCovered(s); setRuleMap(m)
      }
      setLoading(false)
    }
    load()
  }, [])

  function exportNavigator() {
    const techniques = Array.from(covered).map(id => ({
      techniqueID: id, color: '#f97316', comment: 'Covered by SentinelDetect', enabled: true, score: 100,
    }))
    const nav = {
      name: 'SentinelDetect Coverage', versions: { attack: '14', navigator: '4.9', layer: '4.5' },
      domain: 'enterprise-attack', description: 'Generated by SentinelDetect',
      techniques, gradient: { colors: ['#f9f9f9','#f97316'], minValue: 0, maxValue: 100 },
    }
    const a = document.createElement('a')
    a.href = URL.createObjectURL(new Blob([JSON.stringify(nav, null, 2)], { type: 'application/json' }))
    a.download = 'sentineldetect-navigator-layer.json'; a.click()
  }

  const totalTechs   = MITRE.reduce((a, t) => a + t.techs.length, 0)
  const coveredCount = MITRE.reduce((a, t) => a + t.techs.filter(id => covered.has(id.toUpperCase())).length, 0)
  const pct          = Math.round(coveredCount / totalTechs * 100)

  if (loading) return (
    <div style={{display:'flex', alignItems:'center', justifyContent:'center', minHeight:'60vh', color:'var(--muted)', fontSize:'.88rem'}}>
      Loading coverage data...
    </div>
  )

  return (
    <div style={{padding:'1.4rem'}}>

      {/* Stats row */}
      <div style={{display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:'.75rem', flexWrap:'wrap', gap:'.5rem'}}>
        <div style={{fontSize:'.88rem', fontWeight:700, color:'var(--text)'}}>MITRE ATT&amp;CK Coverage</div>
        <button onClick={exportNavigator} style={{padding:'.35rem .85rem', borderRadius:7, border:'1px solid var(--border)', background:'var(--bg4)', color:'var(--muted)', fontSize:'.72rem', cursor:'pointer', fontFamily:'inherit', display:'flex', alignItems:'center', gap:'.35rem'}}>
           Export Navigator JSON
        </button>
      </div>
      <div style={{display:'flex', gap:'1rem', marginBottom:'1.25rem', flexWrap:'wrap'}}>
        {[
          {n: coveredCount, l: 'Techniques covered', c: 'var(--green)'},
          {n: totalTechs - coveredCount, l: 'Gaps remaining', c: 'var(--muted2)'},
          {n: `${pct}%`, l: 'Coverage', c: '#f97316'},
          {n: MITRE.length, l: 'Tactics tracked', c: 'var(--blue)'},
        ].map((s,i) => (
          <div key={i} style={{background:'var(--bg4)', border:'1px solid var(--border)', borderRadius:10, padding:'.75rem 1.1rem', minWidth:120}}>
            <div style={{fontSize:'1.5rem', fontWeight:800, color:s.c, letterSpacing:'-.02em'}}>{s.n}</div>
            <div style={{fontSize:'.68rem', color:'var(--muted)', textTransform:'uppercase', letterSpacing:'.07em', marginTop:'.1rem'}}>{s.l}</div>
          </div>
        ))}
        {/* Progress bar */}
        <div style={{flex:1, minWidth:200, background:'var(--bg4)', border:'1px solid var(--border)', borderRadius:10, padding:'.75rem 1.1rem', display:'flex', alignItems:'center', gap:'1rem'}}>
          <div style={{flex:1, background:'var(--bg3)', borderRadius:999, height:8, overflow:'hidden'}}>
            <div style={{width:`${pct}%`, height:'100%', background:'#f97316', borderRadius:999, transition:'width .5s ease'}}/>
          </div>
          <span style={{fontSize:'.75rem', color:'var(--muted)', fontFamily:'var(--font-mono)', flexShrink:0}}>{pct}%</span>
        </div>
      </div>

      {/* Legend */}
      <div style={{display:'flex', gap:'1rem', marginBottom:'1rem'}}>
        {[['#34d399','Covered — you have a rule'],['var(--bg3)','No rule yet — click to generate']].map(([c,l])=>(
          <div key={l} style={{display:'flex', alignItems:'center', gap:'.4rem', fontSize:'.72rem', color:'var(--muted)'}}>
            <span style={{width:10, height:10, borderRadius:2, background:c, flexShrink:0}}/>
            {l}
          </div>
        ))}
      </div>

      {/* Matrix grid */}
      <div style={{display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(140px, 1fr))', gap:'.6rem'}}>
        {MITRE.map(tactic => {
          const coveredInTactic = tactic.techs.filter(id => covered.has(id.toUpperCase())).length
          return (
            <div key={tactic.id} style={{background:'var(--bg4)', border:'1px solid var(--border)', borderRadius:10, overflow:'hidden'}}>
              {/* Tactic header */}
              <div style={{
                padding:'.45rem .6rem', borderBottom:'1px solid var(--border)',
                background: coveredInTactic > 0 ? 'rgba(52,211,153,.08)' : 'var(--bg3)',
                display:'flex', alignItems:'center', justifyContent:'space-between',
              }}>
                <span style={{fontSize:'.62rem', fontWeight:700, textTransform:'uppercase', letterSpacing:'.07em', color:'var(--muted)'}}>{tactic.tactic}</span>
                <span style={{fontSize:'.58rem', fontFamily:'var(--font-mono)', color: coveredInTactic>0 ? 'var(--green)' : 'var(--muted2)'}}>
                  {coveredInTactic}/{tactic.techs.length}
                </span>
              </div>
              {/* Techniques */}
              <div style={{padding:'.4rem .5rem', display:'flex', flexDirection:'column', gap:'.28rem'}}>
                {tactic.techs.map(tid => {
                  const isCovered = covered.has(tid.toUpperCase())
                  const isHov = hovered === tid
                  return (
                    <div key={tid}
                      onMouseEnter={() => setHovered(tid)}
                      onMouseLeave={() => setHovered(null)}
                      title={isCovered ? ` ${ruleMap[tid.toUpperCase()] || tid}` : `No rule for ${tid} — click to generate`}
                      style={{
                        padding:'.22rem .45rem', borderRadius:4, fontSize:'.63rem',
                        fontFamily:'var(--font-mono)', cursor: isCovered ? 'default' : 'pointer',
                        transition:'all .12s',
                        background: isCovered ? 'rgba(52,211,153,.15)' : isHov ? 'rgba(249,115,22,.12)' : 'var(--bg3)',
                        color: isCovered ? 'var(--green)' : isHov ? '#f97316' : 'var(--muted2)',
                        border: isCovered ? '1px solid rgba(52,211,153,.3)' : isHov ? '1px solid rgba(249,115,22,.3)' : '1px solid transparent',
                        display:'flex', alignItems:'center', justifyContent:'space-between', gap:'.3rem',
                      }}
                      onClick={() => {
                        if (!isCovered) {
                          const url = `/generate?prefill=${encodeURIComponent('Detect MITRE ATT&CK technique '+tid+' ('+tactic.tactic+')')}`
                          window.location.href = url
                        }
                      }}>
                      <span>{tid}</span>
                      {isCovered && <span style={{fontSize:'.55rem'}}></span>}
                    </div>
                  )
                })}
              </div>
            </div>
          )
        })}
      </div>

      <p style={{marginTop:'1.25rem', fontSize:'.72rem', color:'var(--muted2)'}}>
        Click any uncovered technique to pre-fill a detection scenario and generate a rule for it.
      </p>
    </div>
  )
}
